(ns bible.main-test
  (:use [cljd.test :only [deftest is]]
        [bible.widget-helper :only [deftest-widget should-find-one]])
  (:require ["package:flutter/material.dart" :as m]
            [bible.widget-helper :as helper]
            [bible.main :as sut]))

(deftest-widget books-header [{:keys [pumpWidget]}]
  (await (pumpWidget (sut/app)))
  (should-find-one (helper/find-text "Bible")))

(deftest-widget list-names-of-books [{:keys [pumpWidget]}]
  (await (pumpWidget (sut/app)))
  (should-find-one (helper/find-text "Genesis"))
  (should-find-one (helper/find-text "Exodus"))
  (should-find-one (helper/find-text "Leviticus"))
  (should-find-one (helper/find-text "Numbers")))
