(ns bible.memory-http
  (:require [bible.http :as http]))

(def responses (atom {}))
(defn clear! [] (reset! responses {}))

(defprotocol IMockHttp
  (respond-with [_this _method _url _response] "Responds to requests made to the URL using method with response."))

(deftype MemoryHttp []
  http/IHttp
  (-get! [_this url]
    (let [response (first (get-in @responses [:get url]))]
      (swap! responses update-in [:get url] rest)
      (Future/value response)))

  IMockHttp
  (respond-with [_this method url response]
    (swap! responses update-in [method url] conj response)))
