(ns bible.memory-http
  (:require [bible.http :as http]))

(def responses (atom {}))
(defn clear! [] (reset! responses {}))

(defprotocol IMockHttp
  (respond-with [_this _method _uri _response] "Responds to requests made to the uri using method with response."))

(deftype MemoryHttp []
  http/IHttp
  (-get! [_this uri]
    (let [response (first (get-in @responses [:get uri]))]
      (swap! responses update-in [:get uri] rest)
      (Future/value response)))

  IMockHttp
  (respond-with [_this method uri response]
    (swap! responses update-in [method uri] conj response)))
